runtime: python27
api_version: 1
threadsafe: true

# Big ole big instances
instance_class: F4_1G

# Make sure we always have some instances live.
automatic_scaling:
  min_idle_instances: 40

error_handlers:
  - file: build/index.html

handlers:
  # Root
  - url: /?$
    secure: always
    static_files: build/index.html
    upload: build/(.*)
    http_headers:
      Access-Control-Allow-Origin: '*'
      X-Frame-Options: "DENY"
      Strict-Transport-Security: "max-age=2592000; includeSubdomains"
      X-Content-Type-Options: "nosniff"
      X-XSS-Protection: "1; mode=block"

  # Static assets (anything with a file extension)
  - url: /(.*\..*)
    secure: always
    static_files: build/\1
    upload: build/(.*)
    http_headers:
      Access-Control-Allow-Origin: '*'
      X-Frame-Options: "DENY"
      Strict-Transport-Security: "max-age=2592000; includeSubdomains"
      X-Content-Type-Options: "nosniff"
      X-XSS-Protection: "1; mode=block"

#  # Paths with a trailing slash
#  - url: /(.*\/)
#    secure: always
#    static_files: dist/index.html
#    upload: site/(.*)
#    http_headers:
#      Access-Control-Allow-Origin: '*'
#      X-Frame-Options: "DENY"
#      Strict-Transport-Security: "max-age=2592000; includeSubdomains"
#      X-Content-Type-Options: "nosniff"
#      X-XSS-Protection: "1; mode=block"
#
#  # Paths without a trailing slash
#  - url: /(.*)?
#    secure: always
#    static_files: dist/index.html
#    upload: site/(.*)
#    http_headers:
#      Access-Control-Allow-Origin: '*'
#      X-Frame-Options: "DENY"
#      Strict-Transport-Security: "max-age=2592000; includeSubdomains"
#      X-Content-Type-Options: "nosniff"
#      X-XSS-Protection: "1; mode=block"
